apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellokube
spec:
  selector:
    matchLabels:
        app: hellokube
  replicas: 1
  template:
    metadata:
      labels:
        app: hellokube
    spec:
      containers:
      - name: hellokube
        ports:
        - containerPort:  3000
        image: docker.io/rajeshkankran/hellokube